<?php

namespace App\Filament\Resources\ScheduleResource\Pages;

use App\Filament\Resources\ScheduleResource;
use App\Models\Schedule;
use Filament\Resources\Pages\CreateRecord;

class CreateSchedule extends CreateRecord
{
    protected static string $resource = ScheduleResource::class;

    protected function handleRecordCreation(array $data): Schedule
    {
        $days = $data['days'];
        unset($data['days']);

        $schedule = Schedule::create($data);

        foreach ($days as $day) {
            $schedule->days()->create(['day_of_week' => $day]);
        }

        // Seats are automatically generated by the Schedule model's booted() method
        // No need for manual generation here

        return $schedule;
    }
}
